# Generated by Django 6.0.1 on 2026-02-02 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bill_parts_total_alter_bill_labour_cost_and_more'),
        ('mech', '0003_alter_jobcard_booking_alter_jobcard_mechanic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='jobcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mech.jobcard'),
        ),
    ]
