# Generated by Django 5.2.8 on 2026-02-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_billitem_jobcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_approved_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_submitted_by_mechanic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
