# Generated by Django 6.0.1 on 2026-01-28 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('GENERAL', 'General Service'), ('OIL', 'Oil change'), ('ENGINE', 'Engine work'), ('BRAKE', 'Brake Service'), ('OTHER', 'Other')], max_length=20)),
                ('problem_describtion', models.TextField(blank=True, help_text='Customer can describe their problem here ')),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENING', 'Pending'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'in progress'), ('COMPLETED', 'completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
