# Generated by Django 6.0.1 on 2026-01-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='problem_describtion',
        ),
        migrations.AddField(
            model_name='booking',
            name='problem_description',
            field=models.TextField(blank=True, help_text='Customer can describe their problem here'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('general', 'General Service'), ('oil', 'Oil Change'), ('engine', 'Engine Work'), ('brake', 'Brake Service'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
